"""
Write translations into src/i18n/{ru,en}/<chunk>.ts.

Translators (people or agents) return JSON, never TypeScript. Escaping a quote,
a backslash or a «guillemet» by hand inside a TS string literal across 1500
entries is where a dictionary breaks, and a broken dictionary fails the whole
app at import. This file is the only thing that writes those literals.

    python scripts/i18n_write.py keys.json translations/*.json

keys.json    — output of i18n_extract.py (decides which chunk a key lands in)
translations — [{key, ru, en, ru_one?, ru_few?, ru_many?, en_one?, en_other?}]

A translation whose placeholders do not match its key's is REJECTED and listed:
«{n} gün» translated as «{count} дней» would render the literal text «{count}».
"""
import io
import json
import os
import re
import sys

CHUNKS = ["auth", "discover", "workout", "social", "panels", "system", "content", "legal"]


def chunk_for(files, kind):
    f = files[0] if files else ""
    if kind == "data":
        return "content"
    if "/onboarding/" in f or "/auth" in f or f.endswith("auth.ts") or "authGate" in f or "auth-callback" in f:
        return "auth"
    if "/(tabs)/discover" in f or "GymCard" in f or "TrainerRow" in f or "PartnerRow" in f:
        return "discover"
    if "/(tabs)/workout" in f or "/(tabs)/checkin" in f or "saveProgram" in f or "exerciseVideo" in f \
            or "duration" in f or "programDraft" in f or "ProgramCard" in f or "removeWorkout" in f or "removeProgram" in f:
        return "workout"
    if "/(tabs)/feed" in f or "/chat" in f or "chat.ts" in f or "moderation" in f or "CreatorBadge" in f:
        return "social"
    if "/trainer" in f or "/gym" in f or "roles.ts" in f or "gymOwner" in f or "accounts.ts" in f:
        return "panels"
    if "/legal" in f or "legal.ts" in f:
        return "legal"
    return "system"


def ts_str(s):
    """A single-quoted TS string literal, escaped completely."""
    s = s.replace("\\", "\\\\").replace("'", "\\'").replace("\r", "").replace("\n", "\\n")
    return "'" + s + "'"


def placeholders(s):
    return sorted(set(re.findall(r"\{(\w+)\}", s or "")))


def main():
    keys_path = sys.argv[1]
    tr_paths = sys.argv[2:]
    keys = {e["key"]: e for e in json.load(io.open(keys_path, encoding="utf-8"))}

    tr = {}
    for p in tr_paths:
        for item in json.load(io.open(p, encoding="utf-8")):
            if item.get("key") in keys:
                tr[item["key"]] = item

    rejected = []
    books = {lang: {c: [] for c in CHUNKS} for lang in ("ru", "en")}

    for k, meta in keys.items():
        item = tr.get(k)
        if not item:
            continue
        want = placeholders(k)
        chunk = chunk_for(meta["files"], meta["kind"])

        # Russian: a counted key may carry three forms
        ru_forms = {f: item.get("ru_" + f) for f in ("one", "few", "many") if item.get("ru_" + f)}
        if meta.get("counted") and len(ru_forms) == 3:
            bad = [f for f, v in ru_forms.items() if placeholders(v) != want]
            if bad:
                rejected.append((k, "ru plural placeholders " + ",".join(bad)))
            else:
                other = ru_forms["many"]
                books["ru"][chunk].append(
                    "  %s: { one: %s, few: %s, many: %s, other: %s }," % (
                        ts_str(k), ts_str(ru_forms["one"]), ts_str(ru_forms["few"]), ts_str(ru_forms["many"]), ts_str(other)))
        elif item.get("ru"):
            if placeholders(item["ru"]) != want:
                rejected.append((k, "ru placeholders %s != %s" % (placeholders(item["ru"]), want)))
            else:
                books["ru"][chunk].append("  %s: %s," % (ts_str(k), ts_str(item["ru"])))

        en_one, en_other = item.get("en_one"), item.get("en_other")
        if meta.get("counted") and en_one and en_other:
            if placeholders(en_one) != want or placeholders(en_other) != want:
                rejected.append((k, "en plural placeholders"))
            else:
                books["en"][chunk].append(
                    "  %s: { one: %s, other: %s }," % (ts_str(k), ts_str(en_one), ts_str(en_other)))
        elif item.get("en"):
            if placeholders(item["en"]) != want:
                rejected.append((k, "en placeholders %s != %s" % (placeholders(item["en"]), want)))
            else:
                books["en"][chunk].append("  %s: %s," % (ts_str(k), ts_str(item["en"])))

    for lang in ("ru", "en"):
        for c in CHUNKS:
            entries = sorted(set(books[lang][c]))
            path = os.path.join("src", "i18n", lang, c + ".ts")
            body = (
                "import { Dict } from '@/lib/i18n';\n\n"
                "/** %s — %s. Keys are the Azerbaijani source strings, verbatim.\n"
                " *  GENERATED by scripts/i18n_write.py from translator JSON — edit the\n"
                " *  JSON and regenerate; a hand edit here is overwritten. */\n"
                "export const %s: Dict = {\n%s\n};\n" % (c, lang, c, "\n".join(entries))
            )
            io.open(path, "w", encoding="utf-8", newline="\n").write(body)

    total = {lang: sum(len(v) for v in books[lang].values()) for lang in books}
    print("written: ru %d, en %d entries" % (total["ru"], total["en"]))
    print("rejected: %d" % len(rejected))
    for k, why in rejected[:80]:
        print("  - %s  [%s]" % (k[:70], why))


if __name__ == "__main__":
    main()
